### ISSUE TITLE
app deployment

### ISSUE THREAD

**Issue by amoldhillon** [gillbalraj/chat-app#1]
Find a platform to host the app for testing purposes.

**Comment by amoldhillon** [comment]
<img width="960" alt="Capture" src="https://user-images.githubusercontent.com/25551098/54218094-45b03c80-44c3-11e9-84c0-9afb25d53250.PNG">

**Comment by amoldhillon** [comment]
http://chatt-application-demo.herokuapp.com/

Application has been Deployed

// Refer for heroku deployment
   https://www.youtube.com/watch?v=AZNFox2CvBk

**Comment by gillbalraj** [comment]
https://medium.com/codingthesmartway-com-blog/angular-6-mean-stack-crash-course-part-2-implementing-the-back-end-642567e16bb9

We can use this link to create a MEAN App. I'm working on this
